version: '3'
services:
  app:
      build: ./docker/app/
      container_name: wbservice_app
      volumes:
          - ./:/usr/share/nginx/www
      working_dir: /usr/share/nginx/www
      depends_on:
        - postgres
      networks:
        bridge:
          aliases:
          - wbservice_app

  nginx:
      build: ./docker/nginx
      container_name: wbservice
      links:
          - app
      volumes_from:
          - app
      ports:
          - 80:80
      networks:
        bridge:
          aliases:
          - wbservice
 
  postgres:
    image: postgres:10.1
    container_name: postgres-db
    restart: always
    ports:
          - 5432:5432
    environment:
      POSTGRES_DB: wb
      POSTGRES_USER: wbadmin
      POSTGRES_PASSWORD: wbadmin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
        bridge:
          aliases:
          - postgres
  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        bridge:
          aliases:
          - adminer
networks:
  bridge:
    external:
      name: app_bridge
